# -*- coding: utf-8 -*-
"""linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqNM7lcOWONbax6eZwKOX4WuMVA6OYpx
"""

import statistics as st

def linear_regression(Horas,Notas):
    n = len(Horas)
    media_Horas=st.mean(Horas)
    media_Notas=st.mean(Notas)
    covariance=sum((Horas[i] - media_Horas)*(Notas[i]- media_Notas) for i in range(n))
    variance=sum((Horas[i] - media_Horas)** 2 for i in range(n))
    b1=covariance/variance
    b0=media_Notas - b1*media_Horas
    return b1, b0

Horas=[3,4,5,6,7,5,5,10]
Notas=[70,75,90,85,88,90,92,95]

b1, b0 = linear_regression(Horas,Notas)
print('O Coeficiente de interceptação é:' , b1)
print('O Coeficiente de inclinação é:' , b0)





