# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKBqCD9H57pLHGxd5hp2ElL7NILB4bn0
"""

import numpy as np

#adição matrizes
n=np.array([[1,2],[3,4],[5,6]])

o=np.array([[1,1],[2,3],[7,1]])

res1=n+o

print(res1)

q=np.array([[3,2,2]])

u=np.array([[4,2,3]])

res2=q+u

print(res2)

#mostrar matriz transporta
f=np.arange(15).reshape((5,3))

print(f)



