# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1II84GGE5kZSmdNCNc6dsWrDo5rZJOC6y
"""

import pandas as pd
import numpy as np



s1=pd.Series([1,2,-5,0])

s1

s1.values

s1.index

s2=pd.Series([1,2,-5,0], index=['endereço','cidade','cep','número'])

s2

s2.index

s2['a']=1000

s2

s2[s2>0]

s2*2

s2

s2.notnull()

dados={'estado':['SP','MG','PR','SP','MG','PR'],
         'ano':[2019,2019,2019,2020,2020,2020],
         'pop':[45.9,21.2,16.9,46.6,21.4,17.3]}
  df1=pd.DataFrame(dados)

df1

df1.head(2)

df1.tail(2)

df1.sample(2)

"""df2=pd.DataFrame(dados,columns=['ano','estado','pop'])"""

df2

df2['estimativa']=50

df2

df2['estimativa']=np.arange(6)